
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abbas
 */
public class Spelling_Checker extends javax.swing.JFrame {
         
    
    String[] words;     //input words in form of array
    String []  arr;     //Dictionary word copied in this string. 
     int Dic_w;

    /**
     * Creates new form Spelling_Checker
     */
    public Spelling_Checker() {
        initComponents();
        this.Dic_w= Dictionar_words();
        System.out.println(this.Dic_w);
        arr = new String[Dic_w];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Total_w = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        correct_w = new javax.swing.JLabel();
        Mistakes_f = new javax.swing.JLabel();
        bar = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Enter Your Text Below");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(402, 402, 402))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 38, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 311, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search-100.png"))); // NOI18N
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clear.png"))); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Print-100.png"))); // NOI18N
        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Observations");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Total Words:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Percentage Of Errors:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Correct Words:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel27.setText("Mistakes Found:");

        Total_w.setText("-");

        jLabel7.setText("-");

        jLabel16.setText("%");

        correct_w.setText("-");

        Mistakes_f.setText("-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel27))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mistakes_f)
                    .addComponent(correct_w)
                    .addComponent(jLabel16)
                    .addComponent(Total_w))
                .addGap(23, 23, 23))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Total_w))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)
                        .addComponent(jLabel16))
                    .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(correct_w))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Mistakes_f)))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("Corrections ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Word Not Found In Dictionary:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("Replace Mistake With:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("Suggestion:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(129, 129, 129))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Remove Image-100.png"))); // NOI18N
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ignore.png"))); // NOI18N
        jButton2.setText("Ignore");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit Sign Filled-100.png"))); // NOI18N
        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Replace-100.png"))); // NOI18N
        jButton6.setText("Replace");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ignore All.png"))); // NOI18N
        jButton8.setText("Ignore All");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(67, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(224, 224, 224))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Suggestions()
  {
        
        String word=jTextField1.getText();
        char[] words_c=word.toCharArray();
        int arr_length;
        int word_l=word.length();
        for(int a=0;a<arr.length;a++)
        { 
            arr_length=arr[a].length();
          
          
            if(word_l==1)
            {
               if(arr_length<3)
                  jComboBox1.addItem(arr[a]); 
            }
            else if(word_l==2||word_l==3)
            {
                if(arr_length<5)
                
                if(arr[a].charAt(0)==words_c[0] && arr[a].charAt(arr_length-1)==words_c[word_l-1] )
                  jComboBox1.addItem(arr[a]); 
            }
            else if(word_l==4||word_l==5)
            {
                
                if(arr_length<8)
                  if(arr[a].charAt(0)==words_c[0] && arr[a].charAt(arr_length-1)==words_c[word_l-1] )
                  jComboBox1.addItem(arr[a]); 
            }
            else
            {
                  if(arr[a].charAt(0)==words_c[0] && arr[a].charAt(arr_length-1)==words_c[word_l-1] )
                  jComboBox1.addItem(arr[a]); 
            }
 
        }
    }
    
 
    
 private int Dictionar_words()   //Count no of words in dictionary
 {
     int ab=0;
     try
    {
        char[] charArray;
	FileInputStream fstream = new FileInputStream("Dictionary.txt");
        DataInputStream in = new DataInputStream(fstream);
        BufferedReader br = new BufferedReader(new InputStreamReader(in));
        String strLine;				
        
        while ((strLine = br.readLine()) != null)
        {				
            ab++;		
        }
                     
        in.close();
                                        
     }
	catch (Exception e)
	{
	JOptionPane.showMessageDialog(null,e);
	}
     
			return ab;	
   }
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        // Check Button
        
        
    if(jTextArea1.getText().trim().length()==0)
            {
                JOptionPane.showMessageDialog(null,"Please Write something","Error Message",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
               try{
                    
                 
            String text;
            
            text=jTextArea1.getText().trim();
            
         
            words=text.split("[[ ]*|[,]*|[  ]*|[.]*|[:]*|[/]*|[!]*|[?]*|[+]*]+");
         
            
             for(int w=0;w<words.length;w++)
            {
             
                System.out.println(words[w]);
            }
            
          for(int w=0;w<words.length;w++)
            {
             
               words[w]=words[w].toLowerCase();
           }
            int[] Indexing=new int[27];
            int lb;
            int ub;

            try
            {
                
                char[] charArray;
                
                     // Dictionay Work
                FileInputStream fstream = new FileInputStream("Dictionary.txt");
                DataInputStream in = new DataInputStream(fstream);
                BufferedReader br = new BufferedReader(new InputStreamReader(in));
                String strLine;
                int ab=0;
                while ((strLine = br.readLine()) != null)
                {
                    charArray= strLine.toCharArray();
                    if(charArray[0]=='a')
                    {
                        Indexing[0]=ab;
                    }
                    else if(charArray[0]=='b')
                    {
                        Indexing[1]=ab;
                        
                    }
                    else if(charArray[0]=='c')
                    {
                        Indexing[2]=ab;
                        
                    }
                    else if(charArray[0]=='d')
                    {
                        Indexing[3]=ab;
                        
                    }
                    else if(charArray[0]=='e')
                    {
                        Indexing[4]=ab;
                        
                    }
                    else if(charArray[0]=='f')
                    {
                        Indexing[5]=ab;
                        
                    }
                    else if(charArray[0]=='g')
                    {
                        Indexing[6]=ab;
                        
                    }
                    else if(charArray[0]=='h')
                    {
                        Indexing[7]=ab;
                        
                    }
                    else if(charArray[0]=='i')
                    {
                        Indexing[8]=ab;
                        
                    }
                    else if(charArray[0]=='j')
                    {
                        Indexing[9]=ab;
                        
                    }
                    else if(charArray[0]=='k')
                    {
                        Indexing[10]=ab;
                        
                    }
                    else if(charArray[0]=='l')
                    {
                        Indexing[11]=ab;
                        
                    }
                    else if(charArray[0]=='m')
                    {
                        Indexing[12]=ab;
                        
                    }
                    else if(charArray[0]=='n')
                    {
                        Indexing[13]=ab;
                        
                    }
                    else if(charArray[0]=='o')
                    {
                        Indexing[14]=ab;
                        
                    }
                    else if(charArray[0]=='p')
                    {
                        Indexing[15]=ab;
                        
                    }
                    else if(charArray[0]=='q')
                    {
                        Indexing[16]=ab;
                        
                    }
                    else if(charArray[0]=='r')
                    {
                        Indexing[17]=ab;
                        
                    }
                    else if(charArray[0]=='s')
                    {
                        Indexing[18]=ab;
                        
                    }
                    else if(charArray[0]=='t')
                    {
                        Indexing[19]=ab;
                        
                    }
                    else if(charArray[0]=='u')
                    {
                        Indexing[20]=ab;
                        
                    }
                    else if(charArray[0]=='v')
                    {
                        Indexing[21]=ab;
                        
                    }
                    else if(charArray[0]=='w')
                    {
                        Indexing[22]=ab;
                        
                    }
                    else if(charArray[0]=='x')
                    {
                        Indexing[23]=ab;
                        
                    }
                    else if(charArray[0]=='y')
                    {
                        Indexing[24]=ab;
                        
                    }
                    else if(charArray[0]=='z')
                    {
                        Indexing[25]=ab;
                        
                    }
                    else
                     {
                                    
                          Indexing[26]= ab;
                      }	

                    arr[ab]=strLine;
                    ab++;

                }
                in.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,"Dictionary not found");
            }

           

         
            Searching s = new Searching ();
            for (int i=0 ; i< words.length ; i++)
            {
                if(words[i].charAt(0)=='a')
                {
                    lb = 0;
                    ub = Indexing[0];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                            
                        Queue.Enqueue(words[i]);
                        
                    }
                    
                }
                else if(words[i].charAt(0)=='b')
                {
                    lb = Indexing[0]+1;
                    ub = Indexing[1];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                    
                }
                else if(words[i].charAt(0)=='c')
                {
                    lb = Indexing[1]+1;
                    ub = Indexing[2];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                    
                }
                else if(words[i].charAt(0)=='d')
                {
                    lb = Indexing[2]+1;
                    ub = Indexing[3];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                    
                }
                else if(words[i].charAt(0)=='e')
                {
                    lb = Indexing[3]+1;
                    ub = Indexing[4];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);

                        
                    }
                    
                }
                else if(words[i].charAt(0)=='f')
                {
                    lb = Indexing[4]+1;
                    ub = Indexing[5];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);

                        
                    }
                   
                }
                else if(words[i].charAt(0)=='g')
                {
                    lb = Indexing[5]+1;
                    ub = Indexing[6];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);

                        
                    }
                   
                }
                else if(words[i].charAt(0)=='h')
                {
                    lb = Indexing[6]+1;
                    ub = Indexing[7];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='i')
                {
                    lb = Indexing[7]+1;
                    ub = Indexing[8];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);

                        
                    }
                   
                }
                else if(words[i].charAt(0)=='j')
                {
                    lb = Indexing[8]+1;
                    ub = Indexing[9];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);

                        
                    }
                   
                }
                else if (words[i].charAt(0)=='k')
                {
                    lb = Indexing[9]+1;
                    ub = Indexing[10];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);

                        
                    }
                   
                }
                else if(words[i].charAt(0)=='l')
                {
                    lb = Indexing[10]+1;
                    ub = Indexing[11];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);

                        
                    }
                   
                }
                else if(words[i].charAt(0)=='m')
                {
                    lb = Indexing[11]+1;
                    ub = Indexing[12];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='n')
                {
                    lb = Indexing[12]+1;
                    ub = Indexing[13];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='o')
                {
                    lb = Indexing[13]+1;
                    ub = Indexing[14];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='p')
                {
                    lb = Indexing[14]+1;
                    ub = Indexing[15];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='q')
                {
                    lb = Indexing[15]+1;
                    ub = Indexing[16];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='r')
                {
                    lb = Indexing[16]+1;
                    ub = Indexing[17];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='s')
                {
                    lb = Indexing[17]+1;
                    ub = Indexing[18];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='t')
                {
                    lb = Indexing[18]+1;
                    ub = Indexing[19];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='u')
                {
                    lb = Indexing[19]+1;
                    ub = Indexing[20];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='v')
                {
                    lb = Indexing[20]+1;
                    ub = Indexing[21];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='w')
                {
                    lb = Indexing[21]+1;
                    ub = Indexing[22];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='x')
                {
                    lb = Indexing[22]+1;
                    ub = Indexing[23];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='y')
                {
                    lb = Indexing[23]+1;
                    ub = Indexing[24];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                }
                else if(words[i].charAt(0)=='z')
                {
                    lb = Indexing[24]+1;
                    ub = Indexing[25];
                    if(s.BinarySearch(arr, lb, ub, words[i]) == false)
                    {
                        Queue.Enqueue(words[i]);
                        
                    }
                   
                 }
                else	
                                 {	 
                                      lb = Indexing[25]+1;	
                                      ub = Indexing[26]; 
                                      if(s.LinearSearch(arr, lb, ub, words[i]) == false)	
                                      {	 
                                        Queue.Enqueue(words[i]);	
                                          	
                                      }
                          	 }
            }
                                       

            Total_w.setText(""+words.length+"");
            Mistakes_f.setText(""+(Queue.rear+1)+"");
            String correct = Integer.toString(words.length-(Queue.rear+1));
            correct_w.setText(correct);

            int percentage;
            percentage= (Queue.rear+1)*100;
            percentage=percentage/words.length;
            jLabel7.setText(""+percentage+"");

            bar.setValue(percentage);
            jTextField1.setText(Queue.Mistakes[Queue.front]);
            jButton1.setEnabled(false);
            
            Suggestions();
           }
                catch(Exception e)
            {
               JOptionPane.showMessageDialog(null,e);
            }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Clear Button
        jComboBox1.removeAllItems();

        jButton1.setEnabled(true);
        jTextField1.setText("");
        jTextField2.setText("");
         jButton8.setEnabled(true);   
         jButton6.setEnabled(true); 
         jButton3.setEnabled(true);
         jButton2.setEnabled(true);
        jTextArea1.setText("");
        jButton6.setEnabled(true);
        Total_w.setText("-");
        Mistakes_f.setText("-");
        correct_w.setText("-");
        jLabel7.setText("-");
        bar.setValue(0);
        for(int i=0; i<Queue.Mistakes.length; i++){Queue.Mistakes[i]=null;}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Print Button
        
             jComboBox1.removeAllItems();
             jTextArea1.setText("");
             jTextArea1.append("Corrected Text:\n\n");
        

        for(int i=0; i<words.length; i++)
        {
        if(words[i]=="")
        {
            jTextArea1.append(words[i]);
        }
         else
           jTextArea1.append(" "+words[i]);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Remove Button
        
            for(int i=0; i<words.length; i++)
            {
               
                if(words[i]==Queue.Mistakes[Queue.front])
                {
                    words[i]="";
                }
              
            }
            

        
        Queue.Dequeue();

            if(Queue.rear!=-1)
            {
                jTextField1.setText(Queue.Mistakes[Queue.front]);
                jTextField2.setText("");
            }
            else
            {
                jTextField1.setText("");
                jTextField2.setText("");
                jButton8.setEnabled(false);
                jButton6.setEnabled(false); 
                jButton3.setEnabled(false);
                jButton2.setEnabled(false);  }
                jComboBox1.removeAllItems();
    
                if(jTextField1.getText()!=null)
         {
          Suggestions();
         }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                
        
      
        // Replace Button
        
        if(jTextField2.getText()!=null)
        {
            for(int i=0; i<words.length; i++)
            {
                if(words[i]==Queue.Mistakes[Queue.front])
                {
                    Queue.Mistakes[Queue.front]=jTextField2.getText();
                    words[i]=Queue.Mistakes[Queue.front];
                }
                
            }
            
          Queue.Dequeue();

            if(Queue.rear!=-1)
            {
                jTextField1.setText(Queue.Mistakes[Queue.front]);
                jTextField2.setText("");
            }
            else
            {
                jTextField1.setText("");
                jTextField2.setText("");
                jButton8.setEnabled(false);
                jButton6.setEnabled(false); 
                jButton3.setEnabled(false); 
                jButton2.setEnabled(false);  
            }
        } 
        
         jComboBox1.removeAllItems();
         if(jTextField1.getText()!=null)
         {
          Suggestions();
         }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        // Ignore All Button
                jTextField1.setText("");
                jButton8.setEnabled(false);
                jButton6.setEnabled(false); 
                jButton3.setEnabled(false);
                jButton2.setEnabled(false); 
                jComboBox1.removeAllItems();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // Ignore Button
        Queue.Dequeue();

        if(Queue.rear!=-1)
        {
            jTextField1.setText(Queue.Mistakes[Queue.front]);
            jTextField2.setText("");
        }
        else
        {
            jTextField1.setText("");
            jTextField2.setText("");
            jButton8.setEnabled(false);
            jButton6.setEnabled(false); 
            jButton3.setEnabled(false);
            jButton2.setEnabled(false);   }
            jComboBox1.removeAllItems();
  
            if(jTextField1.getText()!=null)
         {
          Suggestions();
         }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Exit Button
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem()!=null){
            jTextField2.setText(""+jComboBox1.getSelectedItem()+"");
        }
        else
        {
             jTextField2.setText("");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spelling_Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spelling_Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spelling_Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spelling_Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Spelling_Checker catagery = new Spelling_Checker();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        catagery.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        catagery.setPreferredSize(screenSize);
        catagery.setMinimumSize(screenSize);
        catagery.setMaximumSize(screenSize);
        catagery.setBounds(0, 0, WIDTH, HEIGHT);
        catagery.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
        catagery.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mistakes_f;
    private javax.swing.JLabel Total_w;
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel correct_w;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
